### @file Makefile.template

CXX = g++ -std=c++11 # Gnu C++ Compiler
#CXX = icc -std=c++11 # Intel C++ Compiler
STDFLAGS = -Wall -g -O3
LIBRARIES = -lthreadpool -lpthread # Library version
#LIBRARIES = -lpthread # Header-only version

INCLUDE = $(ROOT)/include
LIB = $(ROOT)/lib
CXXFLAGS = $(STDFLAGS) -I$(INCLUDE) -L$(LIB)

.SUFFIXES: .cpp .h .o .exe

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $<

.cpp.exe:
	$(CXX) $(CXXFLAGS) -o $@ $< $(LIBRARIES)

all::

clean::
	rm -f a.out gmon.out *.o *.exe

# Work around strange gmake behaviour, stop it removing intermediate files
.SECONDARY:

